In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [34]:
adult_census = pd.read_csv('data/numerical_data.csv')

In [38]:
adult_census.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25.0,b'Private',226802.0,b'11th',7.0,b'Never-married',b'Machine-op-inspct',b'Own-child',b'Black',b'Male',0.0,0.0,40.0,b'United-States',b'<=50K'
1,38.0,b'Private',89814.0,b'HS-grad',9.0,b'Married-civ-spouse',b'Farming-fishing',b'Husband',b'White',b'Male',0.0,0.0,50.0,b'United-States',b'<=50K'
2,28.0,b'Local-gov',336951.0,b'Assoc-acdm',12.0,b'Married-civ-spouse',b'Protective-serv',b'Husband',b'White',b'Male',0.0,0.0,40.0,b'United-States',b'>50K'
3,44.0,b'Private',160323.0,b'Some-college',10.0,b'Married-civ-spouse',b'Machine-op-inspct',b'Husband',b'Black',b'Male',7688.0,0.0,40.0,b'United-States',b'>50K'
4,18.0,b'?',103497.0,b'Some-college',10.0,b'Never-married',b'?',b'Own-child',b'White',b'Female',0.0,0.0,30.0,b'United-States',b'<=50K'

In [44]:
target_name = "class"
target = adult_census[target_name]
target.head()

0    b'<=50K'
1    b'<=50K'
2     b'>50K'
3     b'>50K'
4    b'<=50K'
Name: class, dtype: object

In [39]:
data = adult_census.drop(columns=[target_name,"workclass","fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","native-country"])
data.head()

    age  capital-gain  capital-loss  hours-per-week
0  25.0           0.0           0.0            40.0
1  38.0           0.0           0.0            50.0
2  28.0           0.0           0.0            40.0
3  44.0        7688.0           0.0            40.0
4  18.0           0.0           0.0            30.0

In [40]:
data.columns

Index(['age', 'capital-gain', 'capital-loss', 'hours-per-week'], dtype='object')

In [41]:
data.shape

(48842, 4)

In [42]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
model = KNeighborsClassifier()
_ = model.fit(data, target)

In [45]:
target_predicted = model.predict(data)

In [46]:
target_predicted[:5]

array(["b'<=50K'", "b'<=50K'", "b'<=50K'", "b'>50K'", "b'<=50K'"],
      dtype=object)

In [47]:
target[:5]

0    b'<=50K'
1    b'<=50K'
2     b'>50K'
3     b'>50K'
4    b'<=50K'
Name: class, dtype: object

In [48]:
target[:5] == target_predicted[:5]

0     True
1     True
2    False
3     True
4     True
Name: class, dtype: bool

In [49]:
(target == target_predicted).mean()

0.8141558494738135